---
name: File-Copy-Link
version: 0.080
author:
  - Robin Barker <rmb1@npl.co.uk>
abstract: ~
license: perl
requires:
  File::Copy: 0
  File::Spec: 0
provides:
  File::Copy::Link:
    file: lib/File/Copy/Link.pm
    version: 0.03
  File::Spec::Link:
    file: lib/File/Spec/Link.pm
    version: 0.05
generated_by: Module::Build version 0.2608
